NEED_PRINT_TIME_FOR_PROGRAMM_WORK = True
NEED_PRINT_TIME_FOR_STEP = False
NEED_PRINT_TIME_FOR_TRAVEL = False
NEED_PRINT_TIME_FOR_COLONYS_TRAVEL = False
NEED_PRINT_TIME_FOR_EXPLORING = False

NEED_PRINT_TIME_FOR_DROP_PHEROMONE = False

NEED_PRINT_PhM = False
NEED_PRINT_TRAVELED_WAY = False
